### ISSUE TITLE
How can I permanently enable minimap from .vimrc?

### ISSUE THREAD

**Issue by mcandre** [severin-lemaignan/vim-minimap#21]
What can I drop into my $HOME/.vimrc in order to turn the minimap on at Vim launch? Could we add this configuration tip to the README?

**Comment by yramagicman** [comment]
Two things:
1. :help is your friend. :help autocmd and :help vimenter will tell you everything you need to know
2. since I've already got it, I might as well share it `autocmd! VimEnter * Minimap`
