### ISSUE TITLE
Would it be possible to use the minimap buffer as navigation?

### ISSUE THREAD

**Issue by mipmip** [severin-lemaignan/vim-minimap#24]
Like in Sublime clicking somewhere in the Minimap buffer to put the cursor to that possition in the editing buffer?

**Comment by severin-lemaignan** [comment]
Yes, would be definitely cool, and not too hard to implement. I do not really have time to dedicated to it, though, but I'd be happy to review a pull request!

**Comment by mipmip** [comment]
Just finished it. I really love it :)
I can submit a pull request, but I need you to apply "fixed autocmd, added toggle, fixed map focus #20" first.

**Comment by severin-lemaignan** [comment]
Merged via #29. Thanks for all your contributions!!
