### ISSUE TITLE
display whitespace indenting in minimap

### ISSUE THREAD

**Issue by mipmip** [severin-lemaignan/vim-minimap#27]
can sent pull request

![schermafbeelding 2015-05-20 om 23 15 40](https://cloud.githubusercontent.com/assets/658612/7736754/6ae0c2a2-ff46-11e4-89d6-661ad6ba1565.png)

**Comment by ryanoasis** [comment]
:+1:

**Comment by mipmip** [comment]
@ryanoasis check my fork.

**Comment by ryanoasis** [comment]
@mipmip looks like your fork has your latest contributions?

hopefully @severin-lemaignan is still maintaining this repo

**Comment by mipmip** [comment]
Yes it has. I tried to contact @severin-lemaignan but I think he's very busy.

**Comment by severin-lemaignan** [comment]
Merged! Thanks for the contribution!
