### ISSUE TITLE
Colors In Minimap

### ISSUE THREAD

**Issue by mrkmndz** [severin-lemaignan/vim-minimap#28]
I'm not sure if this is possible, but if there were to be a way to retrieve the syntax highlighting color of a given token in the code, perhaps the minimap could color the dots it draws?

**Comment by severin-lemaignan** [comment]
The 'dots' are actual (braille) characters, ie 2x3 dot matrices.It is not possible to color them individually. It's a pity :-/

**Comment by joeytwiddle** [comment]
If you are ok with colouring the 2x3 blocks @mrkmndz, then this might help:

- How to [look up the syntax group](http://vim.wikia.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor) for a given line,column in the file.
- Use Vim's [`:redir`](http://vimdoc.sourceforge.net/htmldoc/various.html#:redir) with `:highlight` to extract the colour that syntax group uses.
- Use `:highlight` in the MiniMap window to [highlight specific lines/columns](http://stackoverflow.com/a/1635752/99777) (colour the Braille characters).
