### ISSUE TITLE
Certain fonts not compatible.

### ISSUE THREAD

**Issue by sshbio** [severin-lemaignan/vim-minimap#30]
Maybe a small message like this one could be included into the README?

>   Certain fonts like inconsolata do not display plain dots and empty spaces, but plain dots and circles for braille characters. As a result, you may want to use any other font that display braille characters in a way that suit the minimap plugin, like Ubuntu Mono, or Droid Sans Mono.
>   
>   ***Inconsolata***
>   ![image](https://cloud.githubusercontent.com/assets/7250745/8083430/c48e5c44-0f84-11e5-9cba-20d7e2eac0c5.png)
>   
>   ***Ubuntu Mono***
>   ![image](https://cloud.githubusercontent.com/assets/7250745/8083436/d4aaf9d4-0f84-11e5-9383-cb02bba384bc.png)

**Comment by biotician** [comment]
I tried again with another computer (both were [lubuntu](http://lubuntu.net/)) and all of the font was working correctly! This may come from either my terminal emulator (lxterm in both casem different versions) or the font packages I installed.

**Comment by severin-lemaignan** [comment]
Added your comment to the README. Thanks!
