### ISSUE TITLE
The command is not available in this version

### ISSUE THREAD

**Issue by jrcii** [severin-lemaignan/vim-minimap#31]
http://i.imgur.com/m8uH1OQ.png
:(
I have multiple versions of python installed, with 3 as my default, so I added a python2.7 shebang to the top of minimap.py in an attempt to get this working but no luck. Any idea?

**Comment by severin-lemaignan** [comment]
Your error seems to originate from the command `pyfile` not being available. Do you have vim with Python support enabled?

Since this error is likely not related to vim minimap, I'm closing it for now. Feel free to re-open if necessary!
