### ISSUE TITLE
No such group or event: MinimapUpdate

### ISSUE THREAD

**Issue by wddabc** [severin-lemaignan/vim-minimap#39]
Hi, I'm facing as titled when running :Minimap, it shows:

```
Error detected while processing function minimap#ShowMinimap:
line    1:
E216: No such group or event: TextChanged,TextChangedI,BufWinEnter * MinimapUpdate
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/.vim/bundle/vim-minimap/autoload/minimap.py", line 83, in showminimap
    setmmautocmd()
  File "~/.vim/bundle/vim-minimap/autoload/minimap.py", line 58, in setmmautocmd
    vim.command(':autocmd CursorMoved,CursorMovedI,TextChanged,TextChangedI,BufWinEnter * MinimapUpdate')
vim.error
```
When I run :au MinimapUpdate it shows 'No such group or event: MinimapUpdate'
this is my .vimrc

> set nocompatible
> filetype off
> set rtp+=~/.vim/bundle/Vundle.vim
> call vundle#begin()
> Plugin 'VundleVim/Vundle.vim'
> Plugin 'severin-lemaignan/vim-minimap'
> call vundle#end()
> filetype plugin indent on

**Comment by abc-lab-plymouth-team** [comment]
Can you check your vim version?

The `TextChanged` event is a fairly recent addition. You need Vim 7.4 for it, or a Vim 7.3.882 (approximately) or later.

**Comment by severin-lemaignan** [comment]
Can you check your vim version?

The `TextChanged` event is a fairly recent addition. You need Vim 7.4 for it, or a Vim 7.3.882 (approximately) or later.

**Comment by wddabc** [comment]
Thanks, that solves the problem by upgrading the vim
