### ISSUE TITLE
Curses windows

### ISSUE THREAD

**Issue by Aborres** [severin-lemaignan/vim-minimap#57]
Hi,

I was trying the plugin but it seems that there is something wrong with drawille and windows...?
I am using gvim in Windows 10. Apparently, it uses curses and it doesn't exist in windows.

**Comment by severin-lemaignan** [comment]
@Aborres thank you for reporting the issue.
Can you check whether my last commit fix the issue?

**Comment by Aborres** [comment]
Yes, it fixes it, thank you.

I have strange characters in the minimap but that might be because of the font.

**Comment by severin-lemaignan** [comment]
Yes, you need to install a font that include braille glyphs.

**Comment by Aborres** [comment]
Do you recommend anyone in particular? All I am trying are failing. 
How do you set the minimap to start up with vim? I have tried to add it to my vimrc but it doesn't seem to be working.

**Comment by severin-lemaignan** [comment]
Most 'recent' fonts should support braille patterns. You can check [here](http://www.alanwood.net/unicode/braille_patterns.html) whether the glyphs are present in your current font -- note that the font **used by your terminal emulator** has to have support for vim + minimap to be happy!

To have vim-minimap to start with vim, follow the [installation instructions](https://github.com/severin-lemaignan/vim-minimap) -- if those instructions do not work for you, please report the exact steps you've followed for us to be able to help you.
